# Generated by Django 4.0.6 on 2022-07-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0002_alter_quanlynhanvien_namsinhnv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quanlynhanvien',
            name='namsinhnv',
        ),
    ]
