# Generated by Django 4.0.6 on 2022-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0004_rename_chucvunv_quanlynhanvien_ho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quanlynhanvien',
            old_name='ho',
            new_name='chucvunv',
        ),
        migrations.AddField(
            model_name='quanlynhanvien',
            name='namsinhnv',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
